### PR TITLE
Site URL HTML Escaping Fix

### LINKED ISSUE #168: site_url error when we submit on OSTI test server
See email thread:
Hi Guys,
 
I’ve attached the input label that I originally submitted to the OSTI test server, as well as a screenshot of the corresponding entry on the IAD test site. Note that the input label is in JSON format, since we recently added that as a valid format for a release request. I will try again with XML format to see if that makes any difference.
 
Scott
 
From: "Loubrieu, Thomas G (US 398F)" <thomas.g.loubrieu@jpl.nasa.gov>
Date: Wednesday, March 17, 2021 at 9:30 AM
To: "Joyner, Ronald (US 398G)" <ronald.joyner@jpl.nasa.gov>, "Collins, Scott (US 398F)" <scott.collins@jpl.nasa.gov>
Subject: Re: OSTI error on site_url
 
Hi Ron, Scott
 
Thanks for your feedback Ron.
 
Scott can you provide Ron with the OSTI record on submission of which the error was raised ?
 
Can you also check that the DOI value is valid (ie exists), since Ron mentions it is lacking numbers in the suffix.
 
Thanks,
 
Thomas
 
From: "Joyner, Ronald (US 398G)" <ronald.joyner@jpl.nasa.gov>
Date: Wednesday, March 17, 2021 at 8:02 AM
To: "Loubrieu, Thomas G (US 398F)" <thomas.g.loubrieu@jpl.nasa.gov>
Subject: RE: OSTI error on site_url
 
 
Howdy,
 
>> uid":"10.17189/29348
 
The suffix part appears to be lacking some numbers ?  All of the minted DOIs have a suffix of 7 chars ?
 
RJ
 
 
From: Loubrieu, Thomas G (US 398F) 
Sent: Tuesday, March 16, 2021 3:07 PM
To: Joyner, Ronald (US 398G) <ronald.joyner@jpl.nasa.gov>
Cc: Collins, Scott (US 398F) <scott.collins@jpl.nasa.gov>; Padams, Jordan H (US 398A) <jordan.h.padams@jpl.nasa.gov>
Subject: OSTI error on site_url
 
Hi Ron,
 
Scott who is maintaining/devlopping the DOI service Qui used to work on had an error with the OSTI submission. We would like to have your advice on that and possibly report to OSTI if needed.
 
When Scott submit a DOI to OSTI he’s getting this error back from them:
Registration update failed: {"errors":[{"source":"url","uid":"10.17189/29348","title":"URL https://pds.nasa.gov/ds-view/pds/viewBundle.jsp?identifier=urn%3Anasa%3Apds%3Ainsight_cameras&version=1.0 is not allowed by repository osti.nasapds domain settings."}]}
 
 
Scott will be able to provide you with more details if needed (maybe the full OSTI record which was submitted).
 
Thanks,
 
Thomas

### PR DESCRIPTION
**Pull request by collinss-jpl**
**Summary***
This PR fixes an issue discovered in the DOI core service where the site URL was not HTML encoded in a consistent manner. This more likely than not had caused the site URL error returned by OSTI from a release request. This PR aims to standardize handling of the site url, both when parsing from input XML/JSON labels, as well as when rendering an output template.

There are also additional fixes for a unit test that made faulty assumptions about the order files are visited by the OS when reading all input files from a directory, as well as inconsistent parsing/rendering behavior between XML and JSON formats.

**Test Data and/or Report**
Unit test have been updated where necessary to account for standardization changes to sample input files. Initial regression tests have also been added for the parsers/renderers in the core/outputs package.
[test.txt](https://github.com/NASA-PDS/pds-doi-service/files/6250812/test.txt)

**Related Issues**
- fixes #168

### CODE REVIEW

**Review by nutjob4life — APPROVED** [review]

**Review by nutjob4life — APPROVED** [review]

**Review by nutjob4life — APPROVED** [review]
I get that this is just testing code, yet `pkg_resources` is still the better way to go.

`__file__` should start to give a reflex allergic reaction the more you develop in Python 🤧

**Comment by nutjob4life** [comment]
Here's my vote: 🛳 it!

**Comment by collinss-jpl** [comment]
@nutjob4life Hadn't realized that `resource_filename` could be used to just get a directory path as well, neat! Made the suggested change.

**Review by tloubrieu-jpl — APPROVED** [review]
That looks good to me

**Pull request merged**
